### PR TITLE
Do not allow guest direct access to CR8

### LINKED ISSUE #136: No support for NetBSD/amd64 guest
NetBSD/amd64 as guest (tested with NetBSD as host) crashes during the kernel booting process.

I've recorded it:

```
ftp http://netbsd.org/~kamil/haxm/typescript-netbsd-2018-11-25
script -p ./typescript-netbsd-2018-11-25
```

( Port of NetBSD script(1) to Linux http://netbsd.org/~kamil/lldb/nbscript.c )

Log of HAXM kernel messages:

http://netbsd.org/~kamil/haxm/typescript-netbsd-2018-11-25-dmesg.txt

I was told that NetBSD crashes on a Windows host too (tested by @AlexAltea ).

### PR DESCRIPTION
**Pull request by raphaelning**
Currently, HAXM allows the guest to freely read/write CR8 via the
MOV from/to CR8 instructions, and does not save/restore host CR8
state. But some host OSes are sensitive to unexpected CR8 changes:
for instance, Windows x86_64 stores the current IRQL in CR8, and
if the guest (e.g. NetBSD) overwrites CR8 with a smaller value, the
host will crash (BSOD) shortly after the next VM exit.

Fix this problem by making HAXM intercept every guest access to
CR8: write requests are ignored (hardware/host CR8 untouched),
whereas read requests are serviced using a dummy handler that
always returns 0. This is a hacky approach, but since most guest
OSes do not rely on CR8 (e.g. NetBSD writes 0 to CR8 during boot,
but does not seem to care about the outcome), it is an acceptable
expedient. Proper CR8 virtualization would probably require
collaboration with user space, because CR8 is merely an alias for
APIC.TPR[7:4] (cf. Intel SDM Vol. 3A 10.8.6.1), and APIC emulation
is provided by user space (QEMU).

Fixes #136.

Signed-off-by: Yu Ning <yu.ning@intel.com>

### CODE REVIEW

**Comment by krytarowski** [comment]
It looks like CR8 is set to 0 during boot.

https://nxr.netbsd.org/xref/src/sys/arch/x86/x86/lapic.c#198 lapic_write_tpri()
https://nxr.netbsd.org/xref/src/sys/arch/amd64/amd64/autoconf.c#116 cpu_configure()

CR8 is never read by the NetBSD kernel.

**Comment by krytarowski** [comment]
This should be beneficial also for OpenBSD. They set CR8 to 0 on boot and never read it.

http://src.illumos.org/source/xref/openbsd-src/sys/arch/amd64/amd64/cpu.c#811
http://src.illumos.org/source/xref/openbsd-src/sys/arch/amd64/amd64/autoconf.c#133

**Comment by raphaelning** [comment]
Thanks, but I ran `qemu-system-x86_64.exe -accel hax -cdrom NetBSD-8.0-amd64.iso -m 1G -display gtk` and saw the following in HAXM driver log:

```
haxm_warning:Ignored unsupported CR8 read, returning 0
haxm_warning:Ignored guest CR8 write, val=0x0
haxm_warning:Ignored unsupported CR8 read, returning 0
haxm_warning:Ignored guest CR8 write, val=0x0
haxm_error:
...........hax_teardown_vm
```

The "unsupported CR8 read" warning is from this PR:

https://github.com/intel/haxm/blob/87f326e280acd55744dffe789fb3a8588c8a6c39/core/vcpu.c#L197

**Comment by krytarowski** [comment]
This patch looks good to me. (not sure if I can accept)

**Comment by raphaelning** [comment]
@krytarowski Thanks, we'll run some tests and merge it (probably tomorrow).

File: core/vcpu.c [hunk 1]
```diff
@@ -2788,19 +2787,25 @@ static int exit_cr_access(struct vcpu_t *vcpu, struct hax_tunnel *htun)
...
-    cr_ptr = vcpu_read_cr(state, cr);
 
     switch (vmx(vcpu, exit_qualification).cr.type) {
         case 0: { // MOV CR <- GPR
             uint64_t val = state->_regs[(vmx(vcpu, exit_qualification).cr.gpr)];
+            uint64_t old_val = 0;
 
-            hax_debug("cr_access W CR%d: %08llx -> %08llx\n", cr, cr_ptr, val);
+            if (cr == 8) {
+              // TODO: Redirect CR8 write to user space (emulated APIC.TPR)
```
Comment (wcwang) [inline core/vcpu.c]: 2 more spaces indent is needed.
